_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 77
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 77
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.3
            "6": 4.15.0
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
RESUME:
    value: false
copy:
    value: false
copy_w:
    value: 0.5
dataset:
    value: redial_ours
debug:
    value: false
dislike_score:
    value: 0.3
entity:
    value: null
entity_max_length:
    value: 32
fp16:
    value: false
gradient_accumulation_steps:
    value: 4
learning_rate:
    value: 0.0005
like_score:
    value: 2
log_all:
    value: false
max_grad_norm:
    value: null
max_length:
    value: 200
max_train_steps:
    value: null
model:
    value: microsoft/DialoGPT-small
name:
    value: redial_ours_pre_1127
nei_mer:
    value: true
notsay_score:
    value: 1
num_bases:
    value: 8
num_train_epochs:
    value: 0
num_warmup_steps:
    value: 1389
num_workers:
    value: 0
output_dir:
    value: data/saved/redial_ours_pre_1127
per_device_eval_batch_size:
    value: 128
per_device_train_batch_size:
    value: 32
project:
    value: ecr
prompt_encoder:
    value: null
prompt_max_length:
    value: 200
remove_neg:
    value: false
seed:
    value: 1127
test:
    value: false
text_encoder:
    value: roberta-base
text_tokenizer:
    value: roberta-base
tokenizer:
    value: microsoft/DialoGPT-small
use_new_seed:
    value: false
use_sentiment:
    value: false
use_wandb:
    value: true
weight_decay:
    value: 0.01
weighted_loss:
    value: false
